[program:imtera-reverb]
process_name=%(program_name)s
command=php /var/www/imtera/artisan reverb:start --host=127.0.0.1 --port=8082
autostart=true
autorestart=true
user=kp
redirect_stderr=true
stdout_logfile=/var/www/imtera/storage/logs/reverb.log
stopwaitsecs=10
