[program:imtera-horizon]
process_name=%(program_name)s
command=php /var/www/imtera/artisan horizon
autostart=true
autorestart=true
user=kp
redirect_stderr=true
stdout_logfile=/var/www/imtera/storage/logs/horizon.log
stopwaitsecs=3600
